// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WebApplicationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("FindElements")]
    public partial class FindElementsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FindElements.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FindElements", "\tSo that I can work with multiple browsers\r\n\tI want to issue a find element comma" +
                    "nd to a single driver\r\n\tand have that distributed to multiple drivers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find Elements")]
        [NUnit.Framework.CategoryAttribute("SuperDriver")]
        [NUnit.Framework.CategoryAttribute("FindElements")]
        [NUnit.Framework.TestCaseAttribute("TagName", "a", "3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("TagName", "article", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("TagName", "div", "4", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Id", "name", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ClassName", "test", "2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CssSelector", "nav ul li", "3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("LinkText", "Link B", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Name", "email", "1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("PartialLinkText", "Link", "3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("XPath", "/html/body/main/article/header/h2[1]", "1", new string[0])]
        public virtual void FindElements(string by, string selector, string numberOfMatches, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SuperDriver",
                    "FindElements"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find Elements", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am on the Test Form page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When(string.Format("I select elements \"{0}\" \"{1}\"", by, selector), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then(string.Format("there should be {0}", numberOfMatches), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find Element")]
        [NUnit.Framework.CategoryAttribute("SuperDriver")]
        [NUnit.Framework.CategoryAttribute("FindElement")]
        [NUnit.Framework.TestCaseAttribute("TagName", "h2", "Test Heading", new string[0])]
        [NUnit.Framework.TestCaseAttribute("Id", "testheading", "Test Sub A", new string[0])]
        [NUnit.Framework.TestCaseAttribute("CssSelector", "main h2", "Test Heading", new string[0])]
        [NUnit.Framework.TestCaseAttribute("LinkText", "Link B", "Link B", new string[0])]
        [NUnit.Framework.TestCaseAttribute("XPath", "/html/body/main/article/header/h2[1]", "Test Heading", new string[0])]
        public virtual void FindElement(string by, string selector, string content, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SuperDriver",
                    "FindElement"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find Element", @__tags);
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("I am on the Test Form page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.When(string.Format("I select an element \"{0}\" \"{1}\"", by, selector), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.Then(string.Format("the text should be \"{0}\"", content), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
